-- MySQL Script generated by MySQL Workbench
-- Sat Jul  5 01:39:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gestion_rh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestion_rh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestion_rh` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `gestion_rh` ;

-- -----------------------------------------------------
-- Table `gestion_rh`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_rh`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_rh`.`employes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_rh`.`employes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code_employe` VARCHAR(20) NULL DEFAULT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `prenom` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telephone` VARCHAR(20) NULL DEFAULT NULL,
  `poste` VARCHAR(100) NULL DEFAULT NULL,
  `service_id` INT NULL DEFAULT NULL,
  `date_embauche` DATE NULL DEFAULT NULL,
  `salaire_base` DECIMAL(10,2) NULL DEFAULT NULL,
  `photo` VARCHAR(255) NULL DEFAULT NULL,
  `cv` VARCHAR(255) NULL DEFAULT NULL,
  `contrat` VARCHAR(255) NULL DEFAULT NULL,
  `statut` ENUM('actif', 'inactif') NULL DEFAULT 'actif',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `code_employe` (`code_employe` ASC) VISIBLE,
  INDEX `service_id` (`service_id` ASC) VISIBLE,
  CONSTRAINT `employes_ibfk_1`
    FOREIGN KEY (`service_id`)
    REFERENCES `gestion_rh`.`services` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_rh`.`absences_exceptionnelles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_rh`.`absences_exceptionnelles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employe_id` INT NOT NULL,
  `date_debut` DATE NOT NULL,
  `date_fin` DATE NOT NULL,
  `motif` TEXT NULL DEFAULT NULL,
  `statut` ENUM('en attente', 'accepté', 'refusé') NULL DEFAULT 'en attente',
  PRIMARY KEY (`id`),
  INDEX `employe_id` (`employe_id` ASC) VISIBLE,
  CONSTRAINT `absences_exceptionnelles_ibfk_1`
    FOREIGN KEY (`employe_id`)
    REFERENCES `gestion_rh`.`employes` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_rh`.`conges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_rh`.`conges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employe_id` INT NOT NULL,
  `date_debut` DATE NOT NULL,
  `date_fin` DATE NOT NULL,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `motif` TEXT NULL DEFAULT NULL,
  `statut` ENUM('en attente', 'accepté', 'refusé') NULL DEFAULT 'en attente',
  PRIMARY KEY (`id`),
  INDEX `employe_id` (`employe_id` ASC) VISIBLE,
  CONSTRAINT `conges_ibfk_1`
    FOREIGN KEY (`employe_id`)
    REFERENCES `gestion_rh`.`employes` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_rh`.`documents_rh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_rh`.`documents_rh` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employe_id` INT NULL DEFAULT NULL,
  `type` VARCHAR(100) NULL DEFAULT NULL,
  `titre` VARCHAR(255) NULL DEFAULT NULL,
  `fichier_url` VARCHAR(255) NULL DEFAULT NULL,
  `date_upload` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `employe_id` (`employe_id` ASC) VISIBLE,
  CONSTRAINT `documents_rh_ibfk_1`
    FOREIGN KEY (`employe_id`)
    REFERENCES `gestion_rh`.`employes` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_rh`.`formations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_rh`.`formations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NOT NULL,
  `date_debut` DATE NULL DEFAULT NULL,
  `date_fin` DATE NULL DEFAULT NULL,
  `formateur` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_rh`.`employe_formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_rh`.`employe_formation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employe_id` INT NOT NULL,
  `formation_id` INT NOT NULL,
  `statut` ENUM('inscrit', 'termine', 'abandonne') NULL DEFAULT 'inscrit',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `employe_id` (`employe_id` ASC, `formation_id` ASC) VISIBLE,
  INDEX `formation_id` (`formation_id` ASC) VISIBLE,
  CONSTRAINT `employe_formation_ibfk_1`
    FOREIGN KEY (`employe_id`)
    REFERENCES `gestion_rh`.`employes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `employe_formation_ibfk_2`
    FOREIGN KEY (`formation_id`)
    REFERENCES `gestion_rh`.`formations` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_rh`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_rh`.`utilisateurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `mot_de_passe` VARCHAR(255) NOT NULL,
  `role` ENUM('admin', 'manager', 'employe') NOT NULL,
  `employe_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  INDEX `employe_id` (`employe_id` ASC) VISIBLE,
  CONSTRAINT `utilisateurs_ibfk_1`
    FOREIGN KEY (`employe_id`)
    REFERENCES `gestion_rh`.`employes` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_rh`.`evaluations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_rh`.`evaluations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employe_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `note` INT NULL DEFAULT NULL,
  `commentaire` TEXT NULL DEFAULT NULL,
  `evaluateur_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `employe_id` (`employe_id` ASC) VISIBLE,
  INDEX `evaluateur_id` (`evaluateur_id` ASC) VISIBLE,
  CONSTRAINT `evaluations_ibfk_1`
    FOREIGN KEY (`employe_id`)
    REFERENCES `gestion_rh`.`employes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `evaluations_ibfk_2`
    FOREIGN KEY (`evaluateur_id`)
    REFERENCES `gestion_rh`.`utilisateurs` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_rh`.`fiche_paie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_rh`.`fiche_paie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employe_id` INT NOT NULL,
  `mois` INT NOT NULL,
  `annee` INT NOT NULL,
  `salaire_brut` DECIMAL(10,2) NULL DEFAULT '0.00',
  `heures_sup` DECIMAL(5,2) NULL DEFAULT '0.00',
  `prime` DECIMAL(10,2) NULL DEFAULT '0.00',
  `retenue` DECIMAL(10,2) NULL DEFAULT '0.00',
  `salaire_net` DECIMAL(10,2) NULL DEFAULT '0.00',
  `pdf_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `employe_id` (`employe_id` ASC) VISIBLE,
  CONSTRAINT `fiche_paie_ibfk_1`
    FOREIGN KEY (`employe_id`)
    REFERENCES `gestion_rh`.`employes` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_rh`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_rh`.`logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `utilisateur_id` INT NOT NULL,
  `action` TEXT NOT NULL,
  `table_modifiee` VARCHAR(100) NULL DEFAULT NULL,
  `id_element` INT NULL DEFAULT NULL,
  `date_action` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `utilisateur_id` (`utilisateur_id` ASC) VISIBLE,
  CONSTRAINT `logs_ibfk_1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `gestion_rh`.`utilisateurs` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_rh`.`mouvements_rh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_rh`.`mouvements_rh` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employe_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `employe_id` (`employe_id` ASC) VISIBLE,
  CONSTRAINT `mouvements_rh_ibfk_1`
    FOREIGN KEY (`employe_id`)
    REFERENCES `gestion_rh`.`employes` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_rh`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_rh`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `destinataire_id` INT NOT NULL,
  `message` TEXT NOT NULL,
  `date_envoi` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `lue` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `destinataire_id` (`destinataire_id` ASC) VISIBLE,
  CONSTRAINT `notifications_ibfk_1`
    FOREIGN KEY (`destinataire_id`)
    REFERENCES `gestion_rh`.`utilisateurs` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_rh`.`presences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_rh`.`presences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employe_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `heure_arrivee` TIME NULL DEFAULT NULL,
  `heure_depart` TIME NULL DEFAULT NULL,
  `statut` ENUM('présent', 'absent', 'en retard') NULL DEFAULT 'présent',
  PRIMARY KEY (`id`),
  INDEX `employe_id` (`employe_id` ASC) VISIBLE,
  CONSTRAINT `presences_ibfk_1`
    FOREIGN KEY (`employe_id`)
    REFERENCES `gestion_rh`.`employes` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
